name: 'Upload Multiple Release Assets'
description: 'Upload multiple release assets to an existing release in your repository using a glob.'
author: 'NBTX'
inputs:
  upload_url:
    description: 'The URL for uploading assets to the release'
    required: true
  targets:
    description: 'A glob of assets to upload'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
